"""Tests that the declared ground truth is actually true of the generated bytes.

Everything downstream is validated against these schemas, so a schema that lies
would make the whole test suite meaningless.
"""

from __future__ import annotations

import datetime as dt
import struct
import zlib

import pytest

from binfer.model import RelationKind
from binfer.stats import is_high_entropy_span
from binfer.synth import (
    FILETIME_EPOCH_OFFSET,
    FORMAT_A_MAGIC,
    FORMAT_A_SIZE,
    FORMAT_A_VERSION,
    FORMAT_B_HEADER_SIZE,
    FORMAT_B_MAGIC,
    FORMAT_B_TRAILER_SIZE,
    FORMAT_C_FLAG_BITS,
    FORMAT_C_HEADER_SIZE,
    FORMAT_C_MAGIC,
    FORMAT_C_RECORD_MAGIC,
    FORMAT_C_RECORD_SIZE,
    FORMAT_D_MAGIC,
    FORMAT_D_NAME_SIZE,
    FORMAT_D_NOTES_OFFSET,
    FORMAT_D_SIZE,
    FORMAT_D_TITLE_SIZE,
    FORMAT_E_HEADER_SIZE,
    FORMAT_E_MAGIC,
    FORMAT_F_MAGIC,
    FORMAT_F_SIZE,
    FORMATS,
    HUNDRED_NS_PER_SECOND,
    TICKS_EPOCH_OFFSET,
    UNIX_2019,
    UNIX_2026,
    build_corpus,
    format_by_key,
    generate,
)

ACCEPTED_YEARS = range(1990, 2041)


def year_of(seconds: float) -> int:
    return dt.datetime.fromtimestamp(seconds, tz=dt.UTC).year


def samples(key: str) -> tuple[bytes, ...]:
    return generate(format_by_key(key))


def test_every_format_has_a_unique_key_and_seed() -> None:
    assert len(FORMATS) >= 5
    assert len({fmt.key for fmt in FORMATS}) == len(FORMATS)
    assert len({fmt.seed for fmt in FORMATS}) == len(FORMATS)


@pytest.mark.parametrize("fmt", FORMATS, ids=lambda fmt: fmt.key)
def test_generation_is_reproducible(fmt) -> None:  # noqa: ANN001
    assert generate(fmt) == generate(fmt)


@pytest.mark.parametrize("fmt", FORMATS, ids=lambda fmt: fmt.key)
def test_declared_fields_fit_inside_every_sample(fmt) -> None:  # noqa: ANN001
    blobs = generate(fmt)
    assert len(blobs) == 24
    for data in blobs:
        for truth in fmt.fields:
            assert truth.offset + truth.size <= len(data)


@pytest.mark.parametrize("fmt", FORMATS, ids=lambda fmt: fmt.key)
def test_declared_type_names_are_accepted_by_themselves(fmt) -> None:  # noqa: ANN001
    for truth in (*fmt.fields, *fmt.record_fields):
        assert truth.type_name in truth.accepted


def test_build_corpus_is_in_memory_and_named_deterministically() -> None:
    corpus = build_corpus(format_by_key("A"), count=6)
    assert corpus.count == 6
    assert corpus.discovered == 6
    assert [sample.name for sample in corpus.samples] == [f"A_{i:03d}.bin" for i in range(6)]
    assert corpus.uniform


def test_unknown_format_key_is_rejected() -> None:
    with pytest.raises(KeyError, match="no synthetic format"):
        format_by_key("Z")


def test_format_a_matches_its_schema() -> None:
    blobs = samples("A")
    assert {len(data) for data in blobs} == {FORMAT_A_SIZE}
    for data in blobs:
        magic, version, flags, counter, ratio, created = struct.unpack_from("<4sHHIfI", data)
        assert magic == FORMAT_A_MAGIC
        assert version == FORMAT_A_VERSION
        assert flags in {0, 1, 2}
        assert 0 < counter < 1 << 24
        assert 0.0 <= ratio <= 1.0
        assert UNIX_2019 <= created < UNIX_2026
        assert data[0x14:] == bytes(FORMAT_A_SIZE - 0x14)


def test_format_b_length_and_checksum_relations_hold() -> None:
    blobs = samples("B")
    assert len({len(data) for data in blobs}) > 1
    for data in blobs:
        magic, version, reserved, payload_length, _serial = struct.unpack_from("<4sHHII", data)
        assert magic == FORMAT_B_MAGIC
        assert (version, reserved) == (1, 0)
        assert payload_length + FORMAT_B_HEADER_SIZE + FORMAT_B_TRAILER_SIZE == len(data)
        stated = struct.unpack_from("<I", data, len(data) - FORMAT_B_TRAILER_SIZE)[0]
        assert stated == zlib.crc32(data[:-FORMAT_B_TRAILER_SIZE])


def test_format_b_payload_is_not_mistaken_for_a_blob() -> None:
    payloads = [data[FORMAT_B_HEADER_SIZE:-FORMAT_B_TRAILER_SIZE] for data in samples("B")]
    assert not is_high_entropy_span(payloads)


def test_format_c_count_and_length_relations_hold() -> None:
    for data in samples("C"):
        magic, count, record_size, payload = struct.unpack_from("<4sIII", data)
        assert magic == FORMAT_C_MAGIC
        assert record_size == FORMAT_C_RECORD_SIZE
        assert payload == count * FORMAT_C_RECORD_SIZE
        assert len(data) == FORMAT_C_HEADER_SIZE + payload
        assert 4 <= count <= 12


def test_format_c_records_carry_the_declared_layout() -> None:
    fmt = format_by_key("C")
    assert fmt.record_size == FORMAT_C_RECORD_SIZE
    for data in samples("C"):
        count = struct.unpack_from("<I", data, 4)[0]
        for index in range(count):
            start = FORMAT_C_HEADER_SIZE + index * FORMAT_C_RECORD_SIZE
            ident, kind, flags, weight, value, tag = struct.unpack_from("<IBBHf4s", data, start)
            assert 0 < ident < 1 << 24
            assert kind in {1, 2, 3}
            assert flags < 1 << FORMAT_C_FLAG_BITS
            assert 0 <= weight < 1000
            assert 0.0 <= value <= 100.0
            assert tag == FORMAT_C_RECORD_MAGIC


def test_format_d_strings_and_pointer_are_real() -> None:
    blobs = samples("D")
    assert {len(data) for data in blobs} == {FORMAT_D_SIZE}
    for data in blobs:
        assert data[:4] == FORMAT_D_MAGIC
        name = data[0x08 : 0x08 + FORMAT_D_NAME_SIZE]
        assert name.rstrip(b"\x00").decode("ascii").isprintable()
        title = data[0x18 : 0x18 + FORMAT_D_TITLE_SIZE]
        assert title.decode("utf-16-le").rstrip("\x00").isprintable()

        pointer = struct.unpack_from("<I", data, 0x38)[0]
        assert FORMAT_D_NOTES_OFFSET < pointer < FORMAT_D_SIZE
        note = data[pointer:].split(b"\x00", 1)[0]
        assert note != b""
        assert note.decode("ascii").isprintable()
        assert data[FORMAT_D_NOTES_OFFSET:].split(b"\x00", 1)[0] != b""


def test_format_e_header_is_honest_and_the_blob_is_opaque() -> None:
    blobs = samples("E")
    for data in blobs:
        magic, version, method, raw_size, blob_size = struct.unpack_from("<4sHHII", data)
        assert magic == FORMAT_E_MAGIC
        assert (version, method) == (1, 8)
        assert 1024 <= raw_size < 3072
        assert blob_size + FORMAT_E_HEADER_SIZE == len(data)
        assert zlib.decompress(data[FORMAT_E_HEADER_SIZE:]) is not None

    assert is_high_entropy_span([data[FORMAT_E_HEADER_SIZE:] for data in blobs])


def test_format_f_timestamps_all_decode_into_the_accepted_band() -> None:
    blobs = samples("F")
    assert {len(data) for data in blobs} == {FORMAT_F_SIZE}
    for data in blobs:
        magic, seconds, millis, filetime, ticks, sequence = struct.unpack_from("<4sIQQQI", data)
        assert magic == FORMAT_F_MAGIC
        assert year_of(seconds) in ACCEPTED_YEARS
        assert year_of(millis / 1000) in ACCEPTED_YEARS
        assert year_of(filetime / HUNDRED_NS_PER_SECOND - FILETIME_EPOCH_OFFSET) in ACCEPTED_YEARS
        assert year_of(ticks / HUNDRED_NS_PER_SECOND - TICKS_EPOCH_OFFSET) in ACCEPTED_YEARS
        assert sequence > 0
        assert data[0x24:] == bytes(FORMAT_F_SIZE - 0x24)


def test_declared_relations_cover_the_interesting_kinds() -> None:
    declared = {relation.kind for fmt in FORMATS for relation in fmt.relations}
    assert declared == set(RelationKind)
